name: setup-serverless
description: Install Serverless Framework
inputs:
  node-version:
    description: Node.js version to install serverless
    required: false
    default: '14.x'
  serverless-version:
    description: Serverless version to install
    required: false
    default: '2.61.0'

runs:
  using: 'composite'
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Serverless ${{ inputs.serverless-version }}
      shell: sh
      run: npm install -g serverless@${{ inputs.serverless-version }}
